//! MemoryStore trait for storage backend abstraction.
//!
//! This trait defines the interface for memory storage backends.
//! Grafeo (acowork-grafeo) is the primary implementation.

use std::time::Duration;

use acowork_core::error::Result;

use crate::types::{
    AutobiographicalNode, DecayConfig, DecayScanResult, Episode, KnowledgeNode,
    MemoryQuery, ProceduralNode, PurgeResult, SearchResult, StoreHealth,
    StoreStats,
};

/// MemoryStore trait — standardized interface for memory storage backends.
///
/// Implementations can be: grafeo-engine (current), Sled, LMDB, remote service,
/// or in-memory mock for testing.
///
/// Design ref: docs/05-memory.md §10.3
pub trait MemoryStore: Send + Sync {
    // ── Episodic layer ───────────────────────────────────────────────────

    /// Store an interaction episode.
    ///
    /// Episode content is stored as-is.
    /// Embedding is generated by Runtime and passed in.
    fn store_episode(&self, episode: &Episode) -> Result<()>;

    /// Search episodic memories by query.
    fn search_episodes(&self, query: &MemoryQuery) -> Result<Vec<SearchResult>>;

    /// Mark episodes as consolidated.
    fn mark_consolidated(&self, ids: &[u64]) -> Result<()>;

    /// Cleanup consolidated episodes older than the given duration.
    fn cleanup_episodes(&self, older_than: Duration) -> Result<u64>;

    /// Retrieve episodes for conversation history.
    ///
    /// If `session_id` is provided, returns episodes for that session ordered by
    /// timestamp descending. Otherwise returns all episodes across all sessions.
    fn get_episodes(&self, session_id: Option<&str>, limit: usize) -> Result<Vec<Episode>>;

    // ── Semantic layer ───────────────────────────────────────────────────

    /// Store or update a knowledge node (Fact/Preference/Relation).
    ///
    /// Fact nodes are automatically deduplicated by (subject, predicate).
    fn store_knowledge(&self, node: &KnowledgeNode) -> Result<()>;

    /// Store or update a procedural memory node.
    fn store_procedural(&self, node: &ProceduralNode) -> Result<()>;

    /// Store or update an autobiographical memory node.
    ///
    /// Status is forced to Active (enforced by schema).
    fn store_autobiographical(&self, node: &AutobiographicalNode) -> Result<()>;

    // ── Unified retrieval ───────────────────────────────────────────────

    /// Hybrid search: vector + full-text + RRF fusion.
    ///
    /// Searches across all labels (Episodic/Knowledge/Procedural/Autobiographical).
    fn hybrid_search(&self, query: &MemoryQuery) -> Result<Vec<SearchResult>>;

    /// Graph expansion: diffuse from seed nodes along edges.
    ///
    /// # Arguments
    /// * `seeds` - Seed nodes from hybrid_search
    /// * `hops` - Maximum expansion depth (capped at 3)
    fn graph_expand(&self, seeds: &[SearchResult], hops: u8) -> Result<Vec<SearchResult>>;

    // ── Forgetting ───────────────────────────────────────────────────────

    /// Run decay scan with the given configuration.
    ///
    /// Implements: decay_score = importance × activity_signal
    /// where activity_signal = clamp(recency_boost + access_boost, floor, 1.0)
    fn run_decay_scan(&self, config: &DecayConfig) -> Result<DecayScanResult>;

    /// Reactivate a Dormant node back to Active.
    fn reactivate_node(&self, node_id: u64) -> Result<()>;

    /// Purge expired Dormant nodes.
    ///
    /// Node is purged if: dormant_age > config.purge_after AND
    /// importance < config.purge_importance_threshold
    fn purge_expired(&self, max_dormant_age: Duration) -> Result<PurgeResult>;

    // ── Lifecycle ───────────────────────────────────────────────────────

    /// Health check for monitoring and diagnostics.
    fn health_check(&self) -> Result<StoreHealth>;

    /// Storage statistics (node counts, storage size, index status).
    fn stats(&self) -> Result<StoreStats>;

    /// Close the store, flushing pending writes.
    fn close(&self) -> Result<()>;
}