//! Memory types for the AgentCowork memory system.
//!
//! These types define the core data structures for the three-layer memory model:
//! - Episodic layer (Episode)
//! - Semantic layer (KnowledgeNode, ProceduralNode)
//! - Autobiographical layer (AutobiographicalNode)
//!
//! Also includes retrieval result types and storage configuration.

use std::collections::HashMap;
use std::time::Duration;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// Re-export from acowork-core
pub use acowork_core::memory::traits::{MemoryNode, PrivacyLevel};

// ============================================================================
// Query Types
// ============================================================================

/// Hint type for retrieval strategy (from memory_hint.type).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum HintType {
    /// Semantic association (s) - broader retrieval
    #[default]
    Semantic,
    /// Factual recall (f) - precise retrieval
    Factual,
    /// Relational diffusion (r) - graph expansion
    Relational,
    /// Identity/preference (i) - autobiographical focus
    Identity,
}

impl HintType {
    pub fn as_str(&self) -> &'static str {
        match self {
            HintType::Semantic => "s",
            HintType::Factual => "f",
            HintType::Relational => "r",
            HintType::Identity => "i",
        }
    }
}

impl std::str::FromStr for HintType {
    type Err = String;
    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s {
            "s" => Ok(HintType::Semantic),
            "f" => Ok(HintType::Factual),
            "r" => Ok(HintType::Relational),
            "i" => Ok(HintType::Identity),
            _ => Err(format!("unknown HintType: {s}")),
        }
    }
}

/// Filter for node type selection.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum NodeTypeFilter {
    /// Episodic layer nodes.
    Episodic,
    /// Knowledge nodes (semantic layer).
    Knowledge,
    /// Procedural nodes (semantic layer).
    Procedural,
    /// Autobiographical nodes.
    Autobiographical,
}

/// Memory query parameters (replaces raw `&str` for future extensibility).
#[derive(Debug, Clone)]
pub struct MemoryQuery {
    /// Text query for hybrid search.
    pub query_text: String,
    /// Optional filters.
    pub filters: MemoryFilters,
    /// Maximum number of results.
    pub limit: usize,
    /// Graph expansion hops (0 = no expansion).
    pub expand_hops: u8,
    /// Minimum relevance score threshold.
    pub min_score: Option<f32>,
    /// Enable abstention (return empty if confidence too low).
    pub abstention_enabled: bool,
    /// Hint type for retrieval strategy optimization.
    pub hint_type: HintType,
    /// Pre-computed embedding vector (generated by Runtime).
    pub embedding: Option<Vec<f32>>,
}

impl MemoryQuery {
    /// Create a new memory query with default settings.
    pub fn new(query_text: impl Into<String>) -> Self {
        Self {
            query_text: query_text.into(),
            filters: MemoryFilters::default(),
            limit: 10,
            expand_hops: 0,
            min_score: None,
            abstention_enabled: false,
            hint_type: HintType::default(),
            embedding: None,
        }
    }

    /// Build a query for per-turn auto-injection.
    ///
    /// Lightweight background context: searches Autobiographical + Episodic
    /// labels, excludes current-session nodes, no graph expansion, low limit.
    pub fn auto_inject(
        query_text: String,
        exclude_session_id: Option<String>,
    ) -> Self {
        Self {
            query_text,
            embedding: None,
            filters: MemoryFilters {
                exclude_session_id,
                ..Default::default()
            },
            limit: 5,
            expand_hops: 0,
            min_score: Some(0.3),
            abstention_enabled: false,
            hint_type: HintType::Identity,
        }
    }

    /// Build a query for LLM-triggered deep recall (memory_recall tool).
    ///
    /// Comprehensive retrieval: searches all four labels, enables graph
    /// expansion, no score filtering — lets the LLM decide relevance.
    pub fn deep_recall(
        query_text: String,
        exclude_session_id: Option<String>,
    ) -> Self {
        Self {
            query_text,
            embedding: None,
            filters: MemoryFilters {
                exclude_session_id,
                ..Default::default()
            },
            limit: 10,
            expand_hops: 2,
            min_score: None,
            abstention_enabled: false,
            hint_type: HintType::Semantic,
        }
    }
}

/// Filters for memory queries.
#[derive(Debug, Clone, Default)]
pub struct MemoryFilters {
    /// Filter by node types.
    pub node_types: Vec<NodeTypeFilter>,
    /// Filter by privacy levels.
    pub privacy_levels: Vec<PrivacyLevel>,
    /// Filter by time range.
    pub time_range: Option<(DateTime<Utc>, DateTime<Utc>)>,
    /// Filter by session ID (include only this session).
    pub session_id: Option<String>,
    /// Exclude nodes belonging to this session.
    ///
    /// Used by per-turn auto-injection to avoid re-injecting summaries
    /// that are already present in the current session's context window.
    pub exclude_session_id: Option<String>,
}

// ============================================================================
// Conflict Detection Types
// ============================================================================

/// Type of knowledge conflict detected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConflictType {
    /// Knowledge has evolved (new info supersedes old).
    Evolution,
    /// Knowledge correction (new info contradicts old).
    Correction,
    /// Cannot determine relationship.
    Ambiguous,
}

/// Signal indicating potential knowledge conflict.
#[derive(Debug, Clone)]
pub struct ConflictSignal {
    /// Semantic similarity score.
    pub semantic_score: f32,
    /// Whether old and new are temporally conflicting.
    pub temporal_conflict: bool,
    /// Whether context suggests negation.
    pub context_negation: bool,
    /// Suggested conflict type.
    pub suggested_type: ConflictType,
    /// Heuristic confidence in detection [0.0, 1.0].
    pub heuristic_confidence: f32,
}

// ============================================================================
// Evaluation Types
// ============================================================================

/// Metrics collected after each retrieval operation.
/// Computed asynchronously to avoid impacting retrieval latency.
#[derive(Debug, Clone, Default)]
pub struct RetrievalMetrics {
    /// Number of results returned.
    pub result_count: usize,
    /// Average relevance score of results.
    pub avg_score: f32,
    /// Highest relevance score.
    pub max_score: f32,
    /// Whether abstention was triggered.
    pub abstention_triggered: bool,
    /// Number of results filtered by min_score threshold.
    pub filtered_count: usize,
    /// Degradation level (0-3).
    pub retrieval_level: u8,
    /// Number of nodes expanded via graph_expand.
    pub graph_expand_nodes: usize,
    /// memory_hint.type used.
    pub hint_type: HintType,
}

// ============================================================================
// Node Labels
// ============================================================================

/// LPG node labels used in the AgentCowork memory system.
pub mod labels {
    /// Episodic memory label (experiential layer).
    pub const EPISODIC: &str = "Episodic";
    /// Knowledge memory label (semantic layer).
    pub const KNOWLEDGE: &str = "Knowledge";
    /// Procedural memory label (behavior patterns).
    pub const PROCEDURAL: &str = "Procedural";
    /// Autobiographical memory label (self-knowledge).
    pub const AUTOBIOGRAPHICAL: &str = "Autobiographical";

    /// All memory labels in a static slice (for iteration).
    pub const ALL: &[&str] = &[EPISODIC, KNOWLEDGE, PROCEDURAL, AUTOBIOGRAPHICAL];
}

/// LPG edge types used in the AgentCowork memory system.
pub mod edge_types {
    /// Knowledge node references another knowledge node.
    pub const REFERENCES: &str = "REFERENCES";
    /// Autobiographical node self-references.
    pub const SELF_REFERENCES: &str = "SELF_REFERENCES";
    /// Knowledge node derived from an episodic node.
    pub const DERIVED_FROM: &str = "DERIVED_FROM";
}

// ============================================================================
// Enums
// ============================================================================

/// Sub-type of a KnowledgeNode.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum KnowledgeSubType {
    /// Objective fact.
    Fact,
    /// User preference or style.
    Preference,
    /// Relationship between entities.
    Relation,
}

impl KnowledgeSubType {
    pub fn as_str(&self) -> &'static str {
        match self {
            KnowledgeSubType::Fact => "Fact",
            KnowledgeSubType::Preference => "Preference",
            KnowledgeSubType::Relation => "Relation",
        }
    }
}

impl std::str::FromStr for KnowledgeSubType {
    type Err = String;
    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s {
            "Fact" => Ok(KnowledgeSubType::Fact),
            "Preference" => Ok(KnowledgeSubType::Preference),
            "Relation" => Ok(KnowledgeSubType::Relation),
            _ => Err(format!("unknown KnowledgeSubType: {s}")),
        }
    }
}

/// Lifecycle status of a memory node.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum NodeStatus {
    /// Normal participation in retrieval.
    Active,
    /// Decayed below threshold — retained but excluded from search.
    Dormant,
    /// Recently created, pending offline confirmation.
    Pending,
}

impl NodeStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            NodeStatus::Active => "Active",
            NodeStatus::Dormant => "Dormant",
            NodeStatus::Pending => "Pending",
        }
    }
}

impl std::str::FromStr for NodeStatus {
    type Err = String;
    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s {
            "Active" => Ok(NodeStatus::Active),
            "Dormant" => Ok(NodeStatus::Dormant),
            "Pending" => Ok(NodeStatus::Pending),
            _ => Err(format!("unknown NodeStatus: {s}")),
        }
    }
}

/// Category of autobiographical memory.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AutobioCategory {
    /// Name, age, location.
    Identity,
    /// Skills, tools.
    Capability,
    /// Constraints, weaknesses.
    Limitation,
    /// Likes, dislikes, style.
    Preference,
    /// Past events, milestones.
    History,
    /// Connections with others.
    Relationship,
}

impl AutobioCategory {
    pub fn as_str(&self) -> &'static str {
        match self {
            AutobioCategory::Identity => "Identity",
            AutobioCategory::Capability => "Capability",
            AutobioCategory::Limitation => "Limitation",
            AutobioCategory::Preference => "Preference",
            AutobioCategory::History => "History",
            AutobioCategory::Relationship => "Relationship",
        }
    }
}

impl std::str::FromStr for AutobioCategory {
    type Err = String;
    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s {
            "Identity" => Ok(AutobioCategory::Identity),
            "Capability" => Ok(AutobioCategory::Capability),
            "Limitation" => Ok(AutobioCategory::Limitation),
            "Preference" => Ok(AutobioCategory::Preference),
            "History" => Ok(AutobioCategory::History),
            "Relationship" => Ok(AutobioCategory::Relationship),
            _ => Err(format!("unknown AutobioCategory: {s}")),
        }
    }
}

// ============================================================================
// Structs
// ============================================================================

/// A single conversation episode (user message + assistant response + context).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Episode {
    /// Session identifier.
    pub session_id: String,
    /// Turn index within the session.
    pub turn_index: u32,
    /// Role: "user" | "assistant" | "tool".
    pub role: String,
    /// Content.
    pub content: String,
    /// Semantic embedding vector (generated by Runtime).
    pub embedding: Option<Vec<f32>>,
    /// Timestamp of the interaction.
    pub timestamp: DateTime<Utc>,
    /// Whether this episode has been consolidated to the semantic layer.
    pub consolidated: bool,
    /// Optional contextual metadata (topic, sentiment, etc.).
    pub metadata: HashMap<String, serde_json::Value>,
    /// Importance score assigned by LLM at write time [0.0, 1.0].
    #[serde(default = "default_importance")]
    pub importance: f32,
}

fn default_importance() -> f32 {
    0.5
}

/// Semantic memory node — fact, preference, or relation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KnowledgeNode {
    /// Subject of the knowledge (usually "user").
    pub subject: String,
    /// Predicate / relation.
    pub predicate: String,
    /// Object / value.
    pub object: String,
    /// Sub-type classification.
    pub sub_type: KnowledgeSubType,
    /// Confidence [0.0, 1.0].
    pub confidence: f32,
    /// Source episode ID (traceability).
    pub source_episode_id: Option<u64>,
    /// Semantic embedding.
    pub embedding: Option<Vec<f32>>,
    /// Lifecycle status.
    pub status: NodeStatus,
    /// Creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Last update timestamp.
    pub updated_at: DateTime<Utc>,
    /// Optional metadata.
    pub metadata: HashMap<String, serde_json::Value>,
}

/// Procedural memory node — behavior pattern.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProceduralNode {
    /// Human-readable name.
    pub name: String,
    /// Trigger condition description.
    pub trigger_condition: String,
    /// Action pattern description.
    pub action_pattern: String,
    /// Number of successful activations.
    pub success_count: u32,
    /// Number of failed activations.
    pub fail_count: u32,
    /// Confidence [0.0, 1.0].
    pub confidence: f32,
    /// How many times this procedure has been activated (retrieved + injected).
    #[serde(default)]
    pub activation_count: u32,
    /// Which skill this procedure was learned from (if applicable).
    #[serde(default)]
    pub source_skill: Option<String>,
    /// How this procedure was learned: "user_feedback", "execution_failure",
    /// "offline_consolidation", "generalization", or "unknown".
    #[serde(default = "default_learned_from")]
    pub learned_from: String,
    /// Semantic embedding.
    pub embedding: Option<Vec<f32>>,
    /// Lifecycle status.
    pub status: NodeStatus,
    /// Creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Last update timestamp.
    pub updated_at: DateTime<Utc>,
    /// Optional metadata.
    pub metadata: HashMap<String, serde_json::Value>,
}

fn default_learned_from() -> String {
    "unknown".to_string()
}

/// Autobiographical memory node — self-knowledge.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutobiographicalNode {
    /// Category of self-knowledge.
    pub category: AutobioCategory,
    /// Key (e.g. "name", "language", "location").
    pub key: String,
    /// Value.
    pub value: String,
    /// Confidence [0.0, 1.0].
    pub confidence: f32,
    /// Source episode ID.
    pub source_episode_id: Option<u64>,
    /// Semantic embedding.
    pub embedding: Option<Vec<f32>>,
    /// Lifecycle status (schema enforces Active).
    pub status: NodeStatus,
    /// Creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Last update timestamp.
    pub updated_at: DateTime<Utc>,
    /// Optional metadata.
    pub metadata: HashMap<String, serde_json::Value>,
}

// ============================================================================
// Retrieval Types
// ============================================================================

/// Source of a retrieval result.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResultSource {
    /// Direct match from hybrid search.
    DirectMatch,
    /// Expanded via graph diffusion.
    GraphExpansion,
}

/// Context source for memory injection priority.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContextSource {
    /// Autobiographical memory (never trimmed).
    Autobiographical,
    /// Core semantic facts.
    SemanticCore,
    /// Procedural behavior patterns.
    Procedural,
    /// User preferences.
    UserPreference,
    /// Learned from failures.
    FailureLesson,
    /// Graph expansion results.
    GraphExpansion,
    /// Episodic layer.
    Episodic,
}

/// A retrieval result with metadata.
#[derive(Debug, Clone)]
pub struct SearchResult {
    /// Memory node content.
    pub content: String,
    /// Label of the memory node.
    pub label: String,
    /// Relevance score [0.0, 1.0].
    pub score: f64,
    /// How this result was obtained.
    pub source: ResultSource,
    /// Estimated token count for context injection.
    pub context_tokens: usize,
    /// Node ID for tracing.
    pub node_id: u64,
    /// Source context for conflict detection.
    pub source_context: Option<String>,
}

/// Memory context for injection into LLM prompts.
#[derive(Debug, Clone)]
pub struct MemoryContext {
    /// Formatted memory content.
    pub content: String,
    /// Injection priority (0 = highest, 7 = lowest).
    pub priority: u8,
    /// Which cognitive layer this came from.
    pub source: ContextSource,
    /// Estimated token count.
    pub estimated_tokens: usize,
}

// ============================================================================
// Storage Configuration Types
// ============================================================================

/// Decay configuration for forgetting mechanism.
#[derive(Debug, Clone)]
pub struct DecayConfig {
    /// Decay rate lambda (default 0.03, half-life ~23 days).
    pub lambda: f32,
    /// Minimum activity floor (default 0.05).
    pub floor: f32,
    /// Access boost per hit (default 0.1).
    pub access_per_hit: f32,
    /// Cap for access boost history (default 0.5).
    pub boost_cap: f32,
    /// Active -> Dormant threshold (default 0.3).
    pub dormant_threshold: f32,
    /// Dormant -> Purge duration (default 90 days).
    pub purge_after: Duration,
    /// Minimum importance for purge path 1 (default 0.5).
    pub purge_importance_threshold: f32,
}

impl Default for DecayConfig {
    fn default() -> Self {
        Self {
            lambda: 0.03,
            floor: 0.05,
            access_per_hit: 0.1,
            boost_cap: 0.5,
            dormant_threshold: 0.3,
            purge_after: Duration::from_secs(90 * 24 * 60 * 60),
            purge_importance_threshold: 0.5,
        }
    }
}

/// Result of a decay scan operation.
#[derive(Debug, Clone, Default)]
pub struct DecayScanResult {
    /// Number of nodes transitioned Active -> Dormant.
    pub to_dormant: u64,
    /// Number of nodes transitioned Dormant -> Active (reactivated).
    pub reactivated: u64,
    /// Number of nodes purged.
    pub purged: u64,
}

/// Result of a purge operation.
#[derive(Debug, Clone, Default)]
pub struct PurgeResult {
    /// Number of nodes actually purged.
    pub purged_count: u64,
    /// Total bytes freed.
    pub bytes_freed: u64,
}

/// Storage health status.
#[derive(Debug, Clone)]
pub struct StoreHealth {
    /// Whether the store is healthy.
    pub is_healthy: bool,
    /// Latency of the last operation in milliseconds.
    pub latency_ms: u64,
    /// Number of errors in the recent window.
    pub error_count: u32,
    /// Error details (None if healthy).
    pub details: Option<String>,
}

/// Storage statistics.
#[derive(Debug, Clone, Default)]
pub struct StoreStats {
    /// Number of episodic nodes.
    pub episode_count: u64,
    /// Total semantic nodes (Active + Dormant).
    pub node_count: u64,
    /// Number of Active semantic nodes.
    pub active_node_count: u64,
    /// Number of Dormant semantic nodes.
    pub dormant_node_count: u64,
    /// Number of edges.
    pub edge_count: u64,
    /// Storage size in bytes.
    pub storage_size_bytes: u64,
    /// Number of indexes (vector + full-text).
    pub index_count: usize,
}